### ISSUE TITLE
vim-eastwood not working

### ISSUE THREAD

**Issue by sarevok-anchev** [venantius/vim-eastwood#12]
My project.clj (snip):
```
  :dependencies [
    [org.clojure/clojure "1.9.0"]
    [jonase/eastwood "0.3.3" :exclusions [org.clojure/clojure]]
  ]
  :profiles {:dev {:dependencies [[jonase/eastwood "0.2.8" :exclusions [org.clojure/clojure]]]}}

```

And ~/.lein/profiles.clj:
```
{:user
  {
    :plugins [
      [cider/cider-nrepl "0.18.0"]
      [lein-cljfmt "0.6.2"]
      [lein-pprint "1.2.0"]
      [jonase/eastwood "0.3.3"]
    ]

    :dependencies [
      [nrepl "0.5.3"]
      [cljfmt "0.6.2"]
    ]
  }
}
```

When I run :SyntasticCheck from vim, nothing happens.

lein eastwood from console works.

Sorry, I'm very new with clojure and barely understand what's going on. I think the problem is that eastwood is somehow not available for using/importing from the repl and thus it won't work from vim, while it does with "lein eastwood".

But from my limited understanding that's what the line in project.clj is supposed to fix.

Any idea what the issue could be?

Clojure 1.9.0 lein 2.8.2

**Comment by venantius** [comment]
Do you have a fireplace connection open?

**Comment by sarevok-anchev** [comment]
Yeah. :Doc etc works.

**Comment by venantius** [comment]
I'm not sure. To be honest I don't use this plugin anymore - it's possible that the underling API in Eastwood has changed since I wrote it.

**Comment by sarevok-anchev** [comment]
Do you know of any alternatives for linting clojure with vim?

**Comment by venantius** [comment]
I did a bit of digging and figured out the problem - at some point in the past few years Syntastic started requiring you to specifically enable the checker, even if it was properly loaded.

If you add the following line to your ~/.vimrc it should work:
```vim
let g:syntastic_clojure_checkers = ['eastwood']
```

I'll update the README now.

**Comment by sarevok-anchev** [comment]
Had that line in .vimrc already, I'm afraid.

**Comment by venantius** [comment]
Hmm!

Please let me know what the output of the following is from vim:
```vim
echo g:syntastic_clojure_checkers
:SyntasticInfo
```

**Comment by sarevok-anchev** [comment]
```
['eastwood']
```

```
Syntastic version: 3.9.0-23 (Vim 800, Linux)
Info for filetype: clojure
Global mode: active
Filetype clojure is active
The current file will be checked automatically
Available checker: eastwood
Currently enabled checker: eastwood
```

Puzzling!

**Comment by venantius** [comment]
Just to make absolutely sure - when you run `lein eastwood`, does the file you're in have errors? If there aren't any issues with the file then nothing will show up in vim.

**Comment by sarevok-anchev** [comment]
Not right now, but I have mangled it on purpose during testing, and nothing shows up from vim when opening a mangled file, or saving it.

Syntastic is working for python and c++.

**Comment by venantius** [comment]
Can I see your .vimrc?

**Comment by sarevok-anchev** [comment]
https://dpaste.de/tTxJ/raw

**Comment by venantius** [comment]
@sarevok-anchev that snippet is no longer there?

**Comment by sarevok-anchev** [comment]
Weird. Maybe github crawls links. Sneaky.

Try this one: https://pastebin.com/Lu2eykpp

**Comment by venantius** [comment]
So, the next two things to check are: (1) once you've opened a file in vim, go back to the REPL. Has the `eastwood.lint` namespace already been imported? If not that's a good sign there's something wrong with the nREPL connection. (2) I'd like to see a copy of a test namespace file so that we can be sure it's the sort of thing vim-eastwood *would* flag.

**Comment by sarevok-anchev** [comment]
I get this on loading the file now:

CompilerException java.lang.ClassNotFoundException: eastwood.lint, compiling:(/tmp/form-init7529796799003025506.clj:1:342) 

It might be related to the issue linked to before (ctrl+f referenced) though. I don't recall seeing it before.

What version of lein and clojure are you on?

**Comment by sarevok-anchev** [comment]
lein eastwood still works:

```
The following form was being processed during the exception:
defn


Shown again with metadata for debugging (some metadata elided for brevity):
^{:line 4} defn


An exception was thrown while analyzing namespace basic.core
Lint results may be incomplete.  If there are compilation errors in
your code, try fixing those.  If not, check above for info on the
exception.
== Linting basic.core-test ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 1
Subprocess failed
```

I simply removed a ( before defn to cause to to error out.

**Comment by venantius** [comment]
Yeah, that tells me that you've got eastwood on your `:plugins` key but it's not in your `:dependencies` for some reason. My Clojure/Lein versions should not be affecting anything but fwiw I'm on Clojure 1.9.0 and Lein 2.8.1

**Comment by venantius** [comment]
Also just to be clear - removing a ( before `defn` will cause Eastwood to *break*, not to lint (that's what the plugin is reporting - an exception, and the line it was reading when it hit it). If the namespace would fail to be reloaded through fireplace, Eastwood will choke when it tries to read it. So if that's how you've been testing this then that would also explain why it's not showing up as a lint marker.

**Comment by venantius** [comment]
By contrast, _this_ will return a lint error for "test expression is always logical true or always logical false":

```clojure
(defn demo []
  (if (true? true)
    1
    2))
```

**Comment by sarevok-anchev** [comment]
You are indeed correct. Where could I read more about the difference between the two (deps & plugins) and what the consequences are?


You are correct, with your demo function there is indeed a red warning.

I have been testing rust, kotlin and python by breaking the syntax, never crossed my mind to do otherwise.

Great that it is working now and thank you very much, but puzzled about the lack of reporting when it's a syntax error. Is there any way to have syntax errors show up with syntastic, clojure and eastwood?

**Comment by venantius** [comment]
> Where could I read more about the difference between the two (deps & plugins) and what the consequences are?

Hoo boy. Complex issues. A starting point would be the guide on writing [Lein plugins](https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md). 

_Basically_ a dep is available to the _program's_ runtime, whereas a plugin is available to the _build system's_ (i.e. Leiningen's) runtime. Unless configured not to do so, Lein starts its on JVM and then starts a second JVM for your program. There's a lot more to it than that and you can configure things in lots of wacky ways. A number of plugins re-write your project.clj dynamically to insert code into your deps, so if you use e.g. [Ultra](https://github.com/venantius/ultra) it's a plugin that inserts itself as a dependency as well so that you can access certain functions from the REPL.

> Great that it is working now and thank you very much, but puzzled about the lack of reporting when it's a syntax error. Is there any way to have syntax errors show up with syntastic, clojure and eastwood?

I have the following line in my .vimrc:

```vim
au Filetype clojure nmap <c-c><c-k> :Require<cr>
```

Personally, I do `<c-c><c-k>` to reload the current namespace via Fireplace instinctively every couple of seconds as I write code, and if there's a syntax error Fireplace will let me know because the REPL will refuse to parse it. I think this type of habitual/instinctive code reloading comes naturally to lisp/clojure devs workin with an nREPL over time and it's a habit I'd encourage you to develop. 

I don't think Eastwood's in-REPL linting functionality is capable of providing the type of reporting that it does as a plugin, because that seems to be wrapping a stacktrace and then reporting back on it. The in-REPL lint just hits the stacktrace and barfs.

I configured vim-eastwood to swallow any stacktraces it encounters by default mostly because they're annoying. It's behavior that we could change if we wanted to but to be honest I don't find the use case that compelling.
